### ISSUE TITLE
有关M

### ISSUE THREAD

**Issue by Holmes-GU** [mapooon/SelfBlendedImages#1]
想问一下fig3 中，Convex Hull之后的的mask是二值的吧（脸部区域为1，其他为0）？然后mask Augmentation之后的M只是脸部区域附近的取值变成了小数，其余不变？

**Comment by dandelion915** [comment]
估计是0-1的灰度图，mask Augmentation以后边界一些地方变成小数就意味着有侵蚀和形变操作了
