### ISSUE TITLE
Would you mind providing docker images through dockerhub or rar files?

### ISSUE THREAD

**Issue by jiaming-lee** [mapooon/SelfBlendedImages#10]
Thanks for your brilliant work. I trained the model according to the official guide on single Tesla V100, and only 0.84 (AUC) on CDF was achieved, even though landmark augmentation was employed. However, I can get the claimed results when using the provided pretrained model. The reason, I guess, may be that the provided dockerfile does not specify the version of the package, which causes the difference in the environment. So, I wonder if you mind providing docker images through docker hub or rar files. Many thanks!

**Comment by mapooon** [comment]
Hi,
I have uploaded the docker image to docker hub.
https://hub.docker.com/r/mapooon/sbi

**Comment by xuyingzhongguo** [comment]
It seems not available now. Could you please upload again?
