### ISSUE TITLE
I can't find the weights folder 

### ISSUE THREAD

**Issue by YU-SHAO-XU** [mapooon/SelfBlendedImages#11]
Hi
According to the readme that i need to place pretrained EfficientNet-B4. in ./weights/ folder, but I can't find the weights folder.

many thanks!

**Comment by mapooon** [comment]
You can make it manually.
`mkdir weights`

**Comment by mapooon** [comment]
The error comes from not installing retinaface.
Please follow the official guide and use the provided docker file to set up your development environment.

**Comment by YU-SHAO-XU** [comment]
Hi 

I run the code to extract video frames and landmarks, the paper says that sample 32 frames per video for inference, but my result only 8 frames and landmarks each video! Is there any wrong !?

many thanks

**Comment by YU-SHAO-XU** [comment]
Hi
I ran the code in (build.sh) by cmd installation of some libraries and created a container by code in (exec.sh), was there any wrong that i have conducted?because I found another issue say that we had to run dockerfiles/Dockerfile!?
