### ISSUE TITLE
Test on FF++

### ISSUE THREAD

**Issue by YU-SHAO-XU** [mapooon/SelfBlendedImages#16]
@mapooon 

I wanna test the FF++ NT dataset and revise u guys provide file - inference_dataset.py as picture~ 
![image](https://user-images.githubusercontent.com/103430440/188882229-cc25bb17-484b-4105-aa63-42dbe1a44ee3.png)

unfortunately there is something wrong 
![image](https://user-images.githubusercontent.com/103430440/188901059-1cb78878-6ea9-44d1-8db8-7e04d6a40d9a.png)

if test on FF++dataset successfully ,it help me a lot!!

Many Thanks
Shawn

**Comment by mapooon** [comment]
Thank you for your issue.
We added FF++ inference code.
