### ISSUE TITLE
SBI dataset

### ISSUE THREAD

**Issue by YU-SHAO-XU** [mapooon/SelfBlendedImages#17]
Hi, i am working on a Knowledge Distillation project, I'm wondering if you have saved the SBI data separately, would you mind provide me data plz?

**Comment by mapooon** [comment]
We do not have saved SBIs because they are generated on the fly during training.
You can do it using the provided code.

**Comment by YU-SHAO-XU** [comment]
Hi

How many sbi data were you generated!?


mapooon ***@***.***> 於 2022年9月14日 週三 晚上11:38寫道：
