### ISSUE TITLE
About error in sbi.py?

### ISSUE THREAD

**Issue by bestalllen** [mapooon/SelfBlendedImages#24]
Mr. Shiohara: when I reproduced the github code in your paper, I encountered a **reorder_landmark** function with an error in **sbi.py**. The error is **index 77 is out of bounds for axis 0 with size 68**. Shouldn't there be only 68 landmarks? Why is index set to 80? I would appreciate it if you could reply！

**Comment by mapooon** [comment]
As described in the guide, we use a 81 points landmark detector.

**Comment by bestalllen** [comment]
I'm sorry, I made an oversight.
