### ISSUE TITLE
How to include landmark augmentation?

### ISSUE THREAD

**Issue by Ankit2527** [mapooon/SelfBlendedImages#26]
Hi @mapooon , 
Can you explain how to included landmark augmentation in the code? I have put the repo inside the mentioned folder, but how do you use it inside the sbi training code?

**Comment by mapooon** [comment]
After executing the command below, it is automatically used in the training code.
```python3
mkdir src/utils/library
git clone https://github.com/AlgoHunt/Face-Xray.git src/utils/library
```
If it is successfully installed, you can see the output `"exist library"` when you run the training.

**Comment by Ankit2527** [comment]
Thank you @mapooon, it worked after changing the paths in the 2 lines above `print('exist library')`.
