### ISSUE TITLE
Can you provide the frame-level AUC on these datasets?

### ISSUE THREAD

**Issue by crywang** [mapooon/SelfBlendedImages#3]
Especially the cross-dataset performance.

**Comment by mapooon** [comment]
As a quick note, our frame-level AUC on CDF is 85.10%.
Setting:
- We used all frames for the evaluation.
- In each frame, we treated the maximum fakeness as the prediction for the frame as in video-level evaluation.
- We assigned confidence 0.5 to frames where no face is detected by retinaface.

For our frame-level results on other datasets, please wait the code release.

**Comment by mapooon** [comment]
The code has been released.
