### ISSUE TITLE
Question about bi_online_generation.py

### ISSUE THREAD

**Issue by diff3ng** [mapooon/SelfBlendedImages#34]
I saw `src/library/bi_online_generation.py` in the previous code. But this file is not in the latest code base and commit history.
According to
https://github.com/mapooon/SelfBlendedImages/blob/9fe4efe1192cb7448fb51a2b97a54e1312188160/src/utils/sbi.py#L26-L31
It seems that `bi_online_generation.py` is needed.
I used the previous code(with `bi_online_generation.py`) for training, and the test results of the model in CDF can reach 0.92, which is consistent with the results you released.
But I use the latest code (without `bi_online_generation.py`) for training, and the test result of the model in CDF is less than 0.8. Does this have anything to do with `bi_online_generation.py`?

**Comment by Andrew-Pei** [comment]
My fault, didn't see this: https://github.com/mapooon/SelfBlendedImages#:~:text=(Option)%20You%20can%20download%20code%20for%20landmark%20augmentation%3A
please close this issue

**Comment by diff3ng** [comment]
My fault, didn't see this: https://github.com/mapooon/SelfBlendedImages#:~:text=(Option)%20You%20can%20download%20code%20for%20landmark%20augmentation%3A

**Comment by zxq99799** [comment]
Hello, are you conducting training and testing under Docker?
