### ISSUE TITLE
Where to download the FF++ side-by-side train.json   val.json    test.json. files

### ISSUE THREAD

**Issue by noobrookieisme** [mapooon/SelfBlendedImages#36]
Where can I download these?     train.json     val.json      test.json. I have downloaded FaceForensics++.
└── data
    └── FaceForensics++
        ├── original_sequences
        │   └── youtube
        │       └── raw
        │           └── videos
        │               └── *.mp4
        ├── train.json
        ├── val.json
        └── test.json

**Comment by Takase-Syunki** [comment]
That issue has already been discussed [here](https://github.com/mapooon/SelfBlendedImages/issues/5).
