### ISSUE TITLE
Split method of DFDC-preview dataset.

### ISSUE THREAD

**Issue by Nku-cs-dsc** [mapooon/SelfBlendedImages#4]
Thanks for your amazing work. In the paper, I saw the SBI achieve great performance in DFDC-preview. I want to follow your work and test the model performance in DFDC-P. However, I can't find the split method of the DFDC-P. It would be appreciated if you can release the method. Thanks!

**Comment by mapooon** [comment]
Thank you for your interest in our work.
You can find the train/test split we used in Table 1 in the function `init_dfdcp()` in `src/inference/datasets.py`.
For ablation in Table 6, we used a tenth of the original training set as validation and the rest for training.

**Comment by Nku-cs-dsc** [comment]
Thank you for your response. But it seems that the function init_dfdcp() needs a JSON file named 'data/DFDCP/dataset.json' to generate data split dict. Can you share this JSON file?

**Comment by mapooon** [comment]
It is included in `dfdc_preview_set.zip` at [the dataset page](https://dfdc.ai/).

**Comment by Nku-cs-dsc** [comment]
Thx！

**Comment by Hai333** [comment]
@Nku-cs-dsc Sorry to bother you, since the DFDC dataset is very large, I want to use the DFDCP dataset, but I can’t find the download link of the dataset on the Internet, can you share it through the cloud disk, or give me a download link？

**Comment by zxq99799** [comment]
Hello, I have been unable to download DFDC preview. Could you please share the cloud drive? Thank you in advance.
