### ISSUE TITLE
DFDC Preview dataset

### ISSUE THREAD

**Issue by bysen32** [mapooon/SelfBlendedImages#44]
Hello, I have been unable to download DFDC preview. Could you please share the cloud drive? Thank you in advance.

**Comment by bysen32** [comment]
finished

**Comment by bysen32** [comment]
finished

**Comment by ValineDragon** [comment]
Hello, I meet the same question, do you know where to download DFDC preview? I can't download it from https://ai.meta.com/datasets/dfdc/
