### ISSUE TITLE
abort {phase}.json

### ISSUE THREAD

**Issue by Elijah-Yi** [mapooon/SelfBlendedImages#5]
Thanks for your contributions.  In the script, I didn't find out how to generate   **{phase}.json** file,  and, what is recorded in the JSON file?

**Comment by towzeur** [comment]
Splits can be found here : https://github.com/ondyari/FaceForensics/tree/master/dataset/splits

**Comment by Elijah-Yi** [comment]
> 
Thanks. But it seems that other datasets are not

**Comment by mapooon** [comment]
The meta files for train/test splits are distributed with the datasets.
Please refer to `data/datasets.md` which I just added.

**Comment by AryaPulkit** [comment]
How can I know about the classes of videos mentioned in train.json, val.json, and test.json?
