### ISSUE TITLE
 amount of data in the training set 

### ISSUE THREAD

**Issue by shui-tian-ju-shi** [mapooon/SelfBlendedImages#50]
Hi, thank you for your excellent work! According to the settings in your paper, is the amount of data in the training set only 720 × 8 × 2 = 11520? I just think this number seems a bit small.  I don't know if my results are affected by the amount of data.

**Comment by mapooon** [comment]
Hi,
Our the actual number of the training set on FF++ is only 720 × 8 = 5760 because our fake data is generated from real data.
SBIs are generated randomly by augmentations (rgb shift, downscale, etc), so our method can generate countless fake samples during training.

**Comment by shui-tian-ju-shi** [comment]
Excellent explanation! Indeed it is. But then I am immediately worried that with only 5760 real samples, will it cause the model to be unable to learn sufficient features of real samples?

**Comment by mapooon** [comment]
We just follow the conventional experimental setting where models are trained on FF++.
You can train your own models with larger dataset to improve performance.

**Comment by shui-tian-ju-shi** [comment]
Thank you for your reply and suggestion！
Best regard！
