### ISSUE TITLE
ModuleNotFoundError: No module named 'retinaface'

### ISSUE THREAD

**Issue by LOOKCC** [mapooon/SelfBlendedImages#6]
where is retinaface？ where to download this github repo?

**Comment by mapooon** [comment]
It is included in building docker.
Please follow our setup guidance.

**Comment by LOOKCC** [comment]
@mapooon  Sorry, it's inconvenient for me to use docker. How can I download and install retinaface by myself?

**Comment by mapooon** [comment]
Some installations including retinaface are seen in `dockerfiles/Dockerfile`.
Because each library is strongly dependent on other library versions, building an environment without docker can lead to many problems and is out of our support.

**Comment by LOOKCC** [comment]
@mapooon Thanks very much for your helping. I will try it.
